### PR TITLE
Add BanManager repository & dependency

### PR DESCRIPTION
**Pull request by scpketer**
Added dependency handler for [BanManager](https://github.com/BanManagement/BanManager) and its repository @ [frostcast](https://ci.frostcast.net/plugin/repository/everything).

### CODE REVIEW

**Comment by EntryPointKR** [comment]
Can you please resolve the conflicts?

**Comment by scpketer** [comment]
@EntryPointKR done.

**Comment by EntryPointKR** [comment]
Nice. Thanks!

**Comment by EntryPointKR** [comment]
And, notice that dep/repo should be placed also in SpigradleProject.groovy for groovy support(using ext).
Related commit: b636eef

**Pull request merged**
